name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
        rust: [stable]
        include:
          - rust: stable
            can-fail: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - name: Log Toolchain Information
        run: |
          rustc --version
          rustfmt --version
          rustup --version
          cargo --version
      - name: Check Formatting
        if: matrix.rust == 'stable'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        continue-on-error: ${{ matrix.can-fail }}
      - name: Test Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          # only build ipp_encoder for now since astro-dnssd is failing currently for ipp_server on ubuntu
          args: --release --all-features --manifest-path "./encoder/Cargo.toml"
        continue-on-error: ${{ matrix.can-fail }}
      - name: Clippy
        run: cargo clippy -- -D clippy::all
        # only clippy ipp_encoder for now since astro-dnssd is failing currently for ipp_server on ubuntu
        working-directory: ./encoder
        continue-on-error: ${{ matrix.can-fail }}
